# Generated by Django 3.2.7 on 2021-12-22 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.TextField()),
                ('image_response', models.JSONField()),
            ],
            options={
                'verbose_name': 'CloudFlare image',
                'verbose_name_plural': 'CloudFlare images',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.TextField(blank=True, null=True, verbose_name='Идентификатор в гугл картах')),
                ('title', models.TextField(blank=True, default='', null=True, verbose_name='Title')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
                ('cid', models.TextField(blank=True, null=True, unique=True, verbose_name='CID в гугл картах')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=500, null=True)),
                ('site', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta', models.TextField(blank=True, default='<meta>', null=True)),
                ('coordinate_html', models.TextField(blank=True, null=True, verbose_name='Координаты')),
                ('position', models.IntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='Позиция в рейтинге')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('rating_user_count', models.IntegerField(blank=True, default=0, null=True)),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Данные JSON')),
                ('detail_data', models.JSONField(blank=True, null=True, verbose_name='Детальные данные JSON')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('isApiData', models.BooleanField(default=False)),
                ('is_redirect', models.BooleanField(default=False)),
                ('redirect', models.TextField(blank=True, default='', null=True)),
                ('cloud_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parsing.cloudimage', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('sorted', models.BooleanField(default=False)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('access', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('wait', 'wait'), ('success', 'success'), ('warning', 'warning'), ('error', 'error')], default='success', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Название запроса',
                'verbose_name_plural': 'Названии запросов',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True)),
                ('is_edit', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='parsing.place')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ReviewType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип отзыва',
                'verbose_name_plural': 'Типы отзывов',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
                ('path', models.TextField(blank=True, null=True, unique=True, verbose_name='Путь')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ReviewPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='parsing.review')),
                ('review_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='parsing.reviewtype')),
            ],
            options={
                'verbose_name': 'Часть отзыва',
                'verbose_name_plural': 'Части отзыва',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='QueryPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ManyToManyField(related_name='queries', to='parsing.Place')),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='parsing.query')),
            ],
            options={
                'verbose_name': 'Запрос - Объект',
                'verbose_name_plural': 'Запросы - Объекты',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='query',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='queries', to='parsing.Tag'),
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=100, null=True, verbose_name='Гендер')),
                ('cloud_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parsing.cloudimage', verbose_name='Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parsing.cloudimage', verbose_name='Image')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='parsing.place')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=250, null=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='parsing.place')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
            },
        ),
    ]
