# Generated by Django 3.2.7 on 2022-09-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='cid',
            field=models.TextField(blank=True, null=True, verbose_name='CID в гугл картах'),
        ),
    ]
