# Generated by Django 3.2.7 on 2021-12-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryplace',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
