# Generated by Django 3.2.7 on 2022-09-12 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_alter_place_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='faq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='parsing.faq'),
        ),
    ]
