# Generated by Django 3.2.7 on 2021-12-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_queryplace_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryplace',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
