# Generated by Django 3.2.7 on 2022-01-11 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_queryplace_date_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ`s',
            },
        ),
        migrations.CreateModel(
            name='FAQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'FAQ question',
                'verbose_name_plural': 'FAQ questions',
                'ordering': ['-pk'],
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='faq',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='FAQ', to='parsing.FAQQuestion'),
        ),
        migrations.AddField(
            model_name='place',
            name='faq',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='parsing.faq'),
        ),
        migrations.AddField(
            model_name='query',
            name='faq',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query', to='parsing.faq'),
        ),
    ]
