# Generated by Django 3.2.7 on 2022-01-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_auto_20220112_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='timetable',
            field=models.TextField(blank=True, null=True),
        ),
    ]
