# Generated by Django 3.2.7 on 2022-02-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0005_place_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='unique_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
