# Generated by Django 3.2.7 on 2022-02-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0006_review_unique_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='unique_text',
            new_name='original_text',
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
