# Generated by Django 3.2.7 on 2021-10-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0008_auto_20211015_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryplace',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='parsing.query'),
        ),
    ]
