# Generated by Django 3.2.7 on 2022-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0008_uniquereviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquereviews',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
