# Generated by Django 3.2.7 on 2022-02-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0010_rename_uniquereviews_uniquereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquereview',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
