# Generated by Django 3.2.7 on 2021-10-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0011_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
