# Generated by Django 3.2.7 on 2021-10-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0012_query_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='cid',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='CID в гугл картах'),
        ),
    ]
