# Generated by Django 3.2.7 on 2022-02-07 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0013_auto_20220207_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cloud_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parsing.cloudimage', verbose_name='Image'),
        ),
    ]
