# Generated by Django 3.2.7 on 2021-10-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0013_place_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('img', models.ImageField(upload_to='attractions')),
            ],
            options={
                'verbose_name': 'Картинка достопримечательности',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='place_images', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='place',
            name='meta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='phone_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='site',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
        migrations.CreateModel(
            name='ReviewGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=250)),
                ('text', models.TextField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_google', to='parsing.place')),
            ],
            options={
                'verbose_name': 'Отзыв с Google',
                'verbose_name_plural': 'Отзывы с Google',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=250, null=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='parsing.place')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attractions', to='parsing.attractionimage')),
            ],
            options={
                'verbose_name': 'Достопричательность',
                'verbose_name_plural': 'Достопричательности',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='attractions',
            field=models.ManyToManyField(related_name='places', to='parsing.Attraction'),
        ),
    ]
