# Generated by Django 3.2.7 on 2022-02-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0014_city_cloud_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
