# Generated by Django 3.2.7 on 2021-10-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0015_place_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
