# Generated by Django 3.2.7 on 2022-02-08 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0016_cityservice_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityservice',
            old_name='archive',
            new_name='access',
        ),
        migrations.AddField(
            model_name='cityservice',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='cityservice',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cityservice',
            name='faq',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_service', to='parsing.faq'),
        ),
        migrations.AddField(
            model_name='cityservice',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityservice',
            name='sorted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cityservice',
            name='status',
            field=models.CharField(blank=True, choices=[('wait', 'wait'), ('success', 'success'), ('warning', 'warning'), ('error', 'error')], default='success', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cityservice',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='city_service', to='parsing.Tag'),
        ),
    ]
