# Generated by Django 3.2.7 on 2022-02-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0017_auto_20220208_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityservice',
            name='date_parsing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
