# Generated by Django 3.2.7 on 2022-02-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0018_cityservice_date_parsing'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquereview',
            name='city_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parsing.cityservice'),
        ),
    ]
