# Generated by Django 3.2.7 on 2022-02-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0019_uniquereview_city_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
