# Generated by Django 3.2.7 on 2022-02-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0020_alter_service_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqquestion',
            options={'ordering': ['pk'], 'verbose_name': 'FAQ question', 'verbose_name_plural': 'FAQ questions'},
        ),
    ]
