# Generated by Django 3.2.7 on 2021-11-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0020_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewgoogle',
            name='author_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviewgoogle',
            name='rating',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
