# Generated by Django 3.2.7 on 2022-02-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0022_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
