# Generated by Django 3.2.7 on 2022-02-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0024_auto_20220218_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityservice',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
