# Generated by Django 3.2.7 on 2021-11-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0024_auto_20211104_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewgoogle',
            options={'ordering': ['-text'], 'verbose_name': 'Отзыв с Google', 'verbose_name_plural': 'Отзывы с Google'},
        ),
        migrations.AddField(
            model_name='place',
            name='coordinate_html',
            field=models.TextField(blank=True, null=True, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='site',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
