# Generated by Django 3.2.7 on 2022-02-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0025_cityservice_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityservice',
            name='review_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='city_services', to='parsing.ReviewType'),
        ),
    ]
