# Generated by Django 3.2.7 on 2022-02-21 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0026_cityservice_review_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='faq',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='parsing.faq'),
        ),
    ]
