# Generated by Django 3.2.7 on 2021-11-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0026_alter_place_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
