# Generated by Django 3.2.7 on 2021-11-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0027_query_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='title',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Title'),
        ),
    ]
