# Generated by Django 3.2.7 on 2021-11-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0029_auto_20211122_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
