# Generated by Django 3.2.7 on 2022-03-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0029_auto_20220305_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordaicookie',
            name='cookies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
