# Generated by Django 3.2.7 on 2022-03-10 12:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0030_alter_wordaicookie_cookies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='city',
            name='county_seat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='zip_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
    ]
