# Generated by Django 3.2.7 on 2021-11-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0030_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='queries', to='parsing.Tag'),
        ),
    ]
