# Generated by Django 3.2.7 on 2022-03-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0031_auto_20220310_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='county_seat',
            new_name='is_county',
        ),
    ]
