# Generated by Django 3.2.7 on 2022-03-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0032_rename_county_seat_city_is_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
