# Generated by Django 3.2.7 on 2022-04-03 20:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0033_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, null=True, size=None),
        ),
    ]
