# Generated by Django 3.2.7 on 2021-11-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0034_auto_20211126_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
