# Generated by Django 3.2.7 on 2021-11-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0036_auto_20211126_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_img_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
