# Generated by Django 3.2.7 on 2021-12-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0039_auto_20211201_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Позиция в рейтинге'),
        ),
    ]
