# Generated by Django 3.2.7 on 2021-12-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0040_review_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='position',
        ),
        migrations.AddField(
            model_name='place',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Позиция в рейтинге'),
        ),
    ]
