# Generated by Django 3.2.7 on 2021-12-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0042_alter_place_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='sorted',
            field=models.BooleanField(default=False),
        ),
    ]
