# Generated by Django 3.2.7 on 2021-12-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0044_alter_place_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
