# Generated by Django 3.2.7 on 2021-12-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0049_query_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_redirect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='redirect',
            field=models.TextField(blank=True, default='00', null=True),
        ),
    ]
