# Generated by Django 3.2.7 on 2021-09-27 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Название запроса',
                'verbose_name_plural': 'Названии запросов',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.TextField()),
                ('data', models.JSONField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='app.querytype')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['-pk'],
            },
        ),
    ]
