# Generated by Django 3.2.7 on 2021-10-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.TextField(unique=True, verbose_name='Идентификатор в гугл картах'),
        ),
        migrations.CreateModel(
            name='QueryPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ManyToManyField(to='app.Place')),
                ('query', models.ManyToManyField(to='app.Query')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'ordering': ['-pk'],
            },
        ),
    ]
