# Generated by Django 3.2.7 on 2021-10-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211014_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queryplace',
            options={'ordering': ['-pk'], 'verbose_name': 'Запрос - Объект', 'verbose_name_plural': 'Запросы - Объекты'},
        ),
    ]
