# Generated by Django 3.2.7 on 2021-09-27 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_querytype_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querytype',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_types', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
