# Generated by Django 3.2.7 on 2021-10-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_queryplace_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='query',
        ),
        migrations.AlterField(
            model_name='queryplace',
            name='place',
            field=models.ManyToManyField(related_name='queries', to='app.Place'),
        ),
        migrations.AlterField(
            model_name='queryplace',
            name='query',
            field=models.ManyToManyField(related_name='places', to='app.Query'),
        ),
    ]
