# Generated by Django 3.2.7 on 2021-09-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_querytype_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='detail_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
