# Generated by Django 3.2.7 on 2021-09-28 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210929_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='app.querytype', verbose_name='Запрос'),
        ),
    ]
