# Generated by Django 3.2.7 on 2021-10-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
