# Generated by Django 3.2.7 on 2021-09-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_query_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
