# Generated by Django 3.2.7 on 2021-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210929_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
