# Generated by Django 3.2.7 on 2021-09-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_query_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='rating',
        ),
    ]
