# Generated by Django 3.2.7 on 2021-10-19 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_alter_queryplace_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
