# Generated by Django 3.2.7 on 2021-09-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_query_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='querytype',
            name='status',
            field=models.CharField(blank=True, choices=[('wait', 'wait'), ('success', 'success'), ('warning', 'warning'), ('error', 'error')], default='success', max_length=100, null=True),
        ),
    ]
