# Generated by Django 3.2.7 on 2021-10-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_place_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.TextField(blank=True, null=True, verbose_name='Идентификатор в гугл картах'),
        ),
    ]
