# Generated by Django 3.2.7 on 2021-10-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_place_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='rating_user_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
