# Generated by Django 3.2.7 on 2021-11-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211103_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewgoogle',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
