# Generated by Django 3.2.7 on 2021-11-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_placephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placephoto',
            name='img_url',
        ),
        migrations.AddField(
            model_name='place',
            name='isApiData',
            field=models.BooleanField(default=False),
        ),
    ]
