# Generated by Django 3.2.7 on 2021-11-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20211111_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='attractions',
            field=models.ManyToManyField(blank=True, null=True, related_name='places', to='app.Attraction'),
        ),
    ]
