# Generated by Django 3.2.7 on 2021-11-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20211125_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewgoogle',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewgoogle',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='meta',
            field=models.TextField(blank=True, default='<meta>', null=True),
        ),
    ]
