# Generated by Django 3.2.7 on 2021-11-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_review_author_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_img',
            field=models.ImageField(blank=True, null=True, upload_to='google_avatars'),
        ),
    ]
