# Generated by Django 3.2.7 on 2021-11-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_review_author_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dependent_site',
            field=models.CharField(blank=True, choices=[('VAeng', 'VAeng'), ('clarion', 'clarion')], max_length=100, null=True, verbose_name='Зависимый сайт'),
        ),
        migrations.AddField(
            model_name='review',
            name='dependent_user_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ID пользователя на зависимом сайте'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_dependent',
            field=models.BooleanField(default=False),
        ),
    ]
