# Generated by Django 3.2.7 on 2021-12-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_query_sorted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='Позиция в рейтинге'),
        ),
    ]
