# Generated by Django 3.2.7 on 2021-12-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20211210_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='path',
            field=models.TextField(blank=True, null=True, verbose_name='Путь'),
        ),
    ]
