# Generated by Django 3.2.7 on 2021-12-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_tag_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='access',
            field=models.BooleanField(default=False),
        ),
    ]
