# Generated by Django 3.2.7 on 2021-12-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_remove_place_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='redirect',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
